# If the plugin should be enabled
enable: true

# If the owner should be checked before issuing the ticket
owner-check: true

# The different tiers of tickets
tiers:
  1:
    # Price of the ticket
    price: 1000

    # The name of the item
    # Can use %shopName% placeholder and HEX colors
    name: "Ticket (Tier I)"

    # The type of the item
    type: "PAPER"

    # If the item should glow
    glowing: true

    # The lore of the item
    # Can use %shopName% placeholder and HEX colors
    lore:
      - "Basic ticket to %warpName%"
      - "Use it precisely!"

  2:
    # Price of the ticket
    price: 2000

    # The name of the item
    # Can use %shopName% placeholder and HEX colors
    name: "Ticket (Tier II)"

    # The type of the item
    type: "PAPER"

    # If the item should glow
    glowing: true

    # The lore of the item
    # Can use %shopName% placeholder and HEX colors
    lore:
      - "Common ticket to %warpName%"
      - "Use it precisely!"
  3:
    # Price of the ticket
    price: 3000

    # The name of the item
    # Can use %shopName% placeholder and HEX colors
    name: "Ticket (Tier III)"

    # The type of the item
    type: "PAPER"

    # If the item should glow
    glowing: true

    # The lore of the item
    # Can use %shopName% placeholder and HEX colors
    lore:
      - "Rare ticket to %warpName%"
      - "Use it precisely!"
  4:
    # Price of the ticket
    price: 4000

    # The name of the item
    # Can use %shopName% placeholder and HEX colors
    name: "Ticket (Tier IV)"

    # The type of the item
    type: "PAPER"

    # If the item should glow
    glowing: true

    # The lore of the item
    # Can use %shopName% placeholder and HEX colors
    lore:
      - "Epic ticket to %warpName%"
      - "Use it precisely!"
  5:
    # Price of the ticket
    price: 5000

    # The name of the item
    # Can use %shopName% placeholder and HEX colors
    name: "Ticket (Tier V)"

    # The type of the item
    type: "PAPER"

    # If the item should glow
    glowing: true

    # The lore of the item
    # Can use %shopName% placeholder and HEX colors
    lore:
      - "Legendary ticket to %warpName%"
      - "Use it precisely!"

messages:
  prefix: "&6&lTickets"
  usage: "&cUsage: /tickets buy <tier> <warp> <quantity?>"
  reloaded: "&aSuccessfully reloaded in %time%ms!"

  # Available placeholders:
  # %warpName%, %price%, %quantity%, %tier% (I, II, III...), %balance%
  insufficient-balance: "&2You need %price% to buy these tickets, but you have %balance%!"
  not-owner: "&4You are not the owner of this warp!"
  not-enough-space: "&c&lYou need more space in the inventory!"
  successful-purchase: "&aYou successfully purchased %quantity% Tier (%tier%) ticket/s for %warpName% for $%price%!"
  warp-not-found: "&cThere is no warp with this name!"
  # Here the only placeholder is %tier%
  no-tier-permission: "&c&lYou don't have permission to purchase Tier %tier% tickets!"