main: org.example.TicketCreator
name: "UltrapixelTicketCreator"
author: "Proto68"
api-version: 1.21
version: 2.1.0
depend: [Vault, CMI]

commands:
  tickets:
    description: Base command for the UTC plugin.
    usage: /tickets <subcommand>

permissions:
  tickets.reload:
    description: Allows the user to reload the UltrapixelTicketCreator configuration.
    default: op
  tickets.buy:
    description: Allows the user to buy tickets using the '/tickets buy' command.
    default: true
  tickets.tier.1:
    description: Allows the player to buy tier I tickets
    default: false
  tickets.tier.2:
    description: Allows the player to buy tier II tickets
    default: false
  tickets.tier.3:
    description: Allows the player to buy tier III tickets
    default: false
  tickets.tier.4:
    description: Allows the player to buy tier IV tickets
    default: false
  tickets.tier.5:
    description: Allows the player to buy tier V tickets
    default: false