main: org.example.TicketCreator
name: "UltrapixelTicketCreator"
author: "Proto68"
api-version: 1.21
version: 1.0
depend: [Vault, CMI]

commands:
  tickets:
    description: Base command for the UTC plugin.
    usage: /<command> <subcommand>

permissions:
  tickets.reload:
    description: Allows the user to reload the UltrapixelTicketCreator configuration.
    default: op
  tickets.buy:
    description: Allows the user to buy tickets using the '/tickets buy' command.
    default: true